### ISSUE TITLE
Truth Table Features/Improvements

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#186]
There are several issues here, and some discussions on Google Groups, about possible improvements to truth tables. I thought I'd gather them all into one issue, since many of them are interconnected.

Bugs:

- [ ]  Truth table problems should not accept "empty" counterexamples as proof that a sentence is a tautology or an argument is valid. (See issues #44 and #183)

Features:

- [ ]  Make the turnstile configurable (to allow, e.g., the double turnstile or the three dots or...) See #9 and #178 
- [ ]  Make other built-in terminology configurable, and select most common defaults by system/textbook. See #9 and #178. (As part of the MultiBook project, I'd prefer to see these two defaults separately configurable, since the textbooks that use my favorite systems don't use my favorite terminology!)
- [ ] Rework/extend the "counterexample" mechanism, so counterexamples need to be justified by truth-table calculations. This could be done by extending the mechanism currently used for validity tables. Instead of a box under the turnstile, there could be a box at the beginning or end of the row, under a column labeled "Counterexample?". That box would, like the turnstile, count as part of the table, and so the table would not be complete until that box was filled, and the table would be wrong if the box is filled incorrectly. 

   (I'm not exactly sure what the correct label for that box is. I'd like to be able to assign questions that ask a student to categorize a sentence as a truth-functional truth, truth-functional falsehood, or truth-functional contingency. In that context, I'd like them to the check boxes that justify their answers. So, for contingency, they need to check two boxes, one for a row on which it is true, and one for a row on which it is false. In that context, "counterexample" is clearly the wrong label.)

- [ ] It should be possible to assign different credit levels for completing the table on the one hand and submitting a counterexample on the other.
- [ ] Integration of truth tables and questions about what they show. We can do this via chaining, but then Carnap doesn't understand the relationship between the table and the question. That limits additional features, like providing useful error messages (#44), scoring the question relative to the table (when the table contains errors). It also introduces a place where instructors can introduce mistakes, by providing the wrong answer key.
- [ ] Provide better feedback when a truth table contains an error. See #44 for @rzach's suggestions. Here are my suggestions:
    - [ ]  "Truth table not complete. Please fill in the highlighted cells". Highlight the cell(s) that still need to be filled. (With an option to disable the highlighting.)
    - [ ]  "Truth table contains an error. Please check the highlighted cells/rows". With options to disable highlighting, and options to highlight just the row(s), or each individual cell.
    - [ ]  "Misidentified counterexample(s)". Option to highlight the row(s) containing the error.
    - [ ]  "Your table is correct, but your answer is wrong. Please check your answer."

- [ ]  Allow what Calgary forallx calls "Truth Table Shortcuts"---marking a disjunction true when one disjunct is true, without calculating the other disjunct; not completing the rest of the truth table once you have shown that it is invalid, etc. <https://groups.google.com/g/carnap-users/c/380fPfB194A>. These should be available both for boxes in the table, and for the "counterexample" boxes.
- [ ] Tweak the styling of the select boxes for each truth table cell. Ideally, something more compact and consistent across browsers, but not anything that decreases accessibility.
- [ ] "Guided" or "training wheels" options:
    - [ ] Highlight the column under the main connective of each sentence.
    - [ ] Highlight the cells from which the value in the currently selected cell should be calculated
    - [ ] Cells are not editable until the cells they depend on have been filled in.
    - [ ] A mode that automatically checks errors. Probably not after each cell is filled in, since that makes it too trivial for the student to fix the error. But maybe every time the main connective of a sentence is filled in. Or maybe after a row is completed. (Combining this together with one of the options to highlight the cell(s) or row(s) with errors could be helpful.)
- [ ] A way for the student to clear out all the cells and start over.

**Comment by liaoshenyi** [comment]
In addition to the issues mentioned above, I wonder if it'd be possible to implement a counterexample-to option for contradiction, which parallels that of tautology?

(This is, I think, literally my first comment ever on GitHub so please let me know if I'm doing it incorrectly!)

**Comment by gleachkr** [comment]
@liaoshenyi welcome to github!

**Comment by gleachkr** [comment]
`counterexample-to="contradiction"` is now implemented! The button label is "Non-Contradiction", paralleling "Non-Tautology". Documenation here: https://carnap.io/srv/doc/truth-tables.md#counterexamples.

**Comment by liaoshenyi** [comment]
@gleachkr Thank you for implementing it quickly. I've tried a couple of different methods, but it doesn't seem like there's a way to ask for counterexample to both tautology and to contradiction in the same question right now? I have in mind the forallx problems of asking whether a sentence is a tautology, a contradiction, or contingent—and approximating that in carnap.

**Comment by gleachkr** [comment]
Yes, there's no good way to do that right now -you can offer "choose one" sets of problems where students need to complete one member of some set, but listing the TT twice would be awkward.

The idea of allowing multiple counterexample types makes sense, and shouldn't be too hard. I'll try to get it done soon.

- [ ] multiple counterexample types

**Comment by rzach** [comment]
Workaround: give them two problems: one is just the truth table, then another is a multiple-choice question asking them if it's a tautology, contradiction, or contingent.
